"""add comments with replies

Revision ID: 1c96c2b4ddfd
Revises: 745bf1d7561c
Create Date: 2025-11-18 16:24:33.009632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c96c2b4ddfd'
down_revision: Union[str, Sequence[str], None] = '745bf1d7561c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
